const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),postgres=require('postgres');
const PORT=Number(process.env.PORT||3000),DIR=fs.existsSync(path.join(__dirname,'dist'))?path.join(__dirname,'dist'):path.join(__dirname,'public');
if(!process.env.DATABASE_URL){console.error('DATABASE_URL is required. Add your Supabase connection string.');process.exit(1)}
const sql=postgres(process.env.DATABASE_URL,{ssl:'require',prepare:false,max:5}),statuses=['Open','In Progress','Closed'];
const send=(res,status,payload,type='application/json; charset=utf-8')=>{res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(typeof payload==='string'||Buffer.isBuffer(payload)?payload:JSON.stringify(payload))};
const body=req=>new Promise((resolve,reject)=>{let value='';req.on('data',c=>value+=c);req.on('end',()=>{try{resolve(value?JSON.parse(value):{})}catch{reject(Error('Invalid JSON body.'))}});req.on('error',reject)});
async function ticket(id){const [row]=await sql`select ticket_id,customer_name,customer_email,subject,description,status,created_at,updated_at from tickets where ticket_id=${id}`;if(!row)return null;row.notes=await sql`select id,note_text,created_at from notes where ticket_id=${id} order by created_at desc`;return row}
async function api(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/tickets'){const status=url.searchParams.get('status')||'',search=(url.searchParams.get('search')||'').trim(),sf=statuses.includes(status)?sql`and status=${status}`:sql``,q=search?`%${search}%`:'';return send(res,200,await sql`select ticket_id,customer_name,customer_email,subject,status,created_at,updated_at from tickets where true ${sf} and (${q}='' or ticket_id ilike ${q} or customer_name ilike ${q} or customer_email ilike ${q} or subject ilike ${q} or description ilike ${q}) order by updated_at desc`)}
 if(req.method==='POST'&&url.pathname==='/api/tickets'){const {customer_name,customer_email,subject,description}=await body(req);if(![customer_name,customer_email,subject,description].every(x=>typeof x==='string'&&x.trim()))return send(res,400,{error:'Name, email, subject, and description are required.'});if(!/^\S+@\S+\.\S+$/.test(customer_email.trim()))return send(res,400,{error:'Enter a valid email address.'});const [row]=await sql`insert into tickets(customer_name,customer_email,subject,description) values(${customer_name.trim()},${customer_email.trim()},${subject.trim()},${description.trim()}) returning ticket_id,created_at`;return send(res,201,row)}
 const match=url.pathname.match(/^\/api\/tickets\/(TKT-\d{4,})$/);if(match&&req.method==='GET'){const row=await ticket(match[1]);return row?send(res,200,row):send(res,404,{error:'Ticket not found.'})}
 if(match&&req.method==='PUT'){const {status,notes}=await body(req);if(status!==undefined&&!statuses.includes(status))return send(res,400,{error:'Invalid status.'});if(!await ticket(match[1]))return send(res,404,{error:'Ticket not found.'});if(status)await sql`update tickets set status=${status} where ticket_id=${match[1]}`;if(typeof notes==='string'&&notes.trim())await sql`insert into notes(ticket_id,note_text) values(${match[1]},${notes.trim()})`;const [row]=await sql`select updated_at from tickets where ticket_id=${match[1]}`;return send(res,200,{success:true,updated_at:row.updated_at})}
 return send(res,404,{error:'API route not found.'});
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml'};
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);const file=path.resolve(DIR,`.${url.pathname==='/'?'/index.html':url.pathname}`);if(!file.startsWith(DIR)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return send(res,404,'Not found','text/plain');send(res,200,fs.readFileSync(file),mime[path.extname(file)]||'application/octet-stream')}catch(error){console.error(error);send(res,500,{error:'Unexpected server error.'})}}).listen(PORT,()=>console.log(`HelioDesk running at http://localhost:${PORT}`));
